server:
  port: 8085

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.169:5432/article_test
    platform: postgres
    username: postgres
    password: "#1026Antock#"

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: 192.168.0.173
    port: 5672
    username: admin
    password: "@1026Antock@"


bigkinds:
  api:
    url: "http://tools.kinds.or.kr:8888/search/news"
